
name = "api-gateway"

compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

main = "./dist/index.js"
format = "modules"

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"

[env.production]
name = "api-gateway-prod"
route = "api-gateway.adevstack.workers.dev/*"
