
name = "api-gateway"
main = "./dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"

[env.production]
vars = { NODE_ENV = "production" }
route = "api-gateway.adevstack.workers.dev/*"
