
name = "apigateway"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[site]
bucket = "./dist/public"

[vars]
NODE_ENV = "production"

[env.production]
name = "apigateway-prod"
route = "apigateway.adevstack.workers.dev/*"
