
name = "api-gateway"  # Corrected: added the hyphen for the correct worker name

compatibility_date = "2024-01-01"

main = "./dist/index.js"

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"

[env.production]
name = "api-gateway-prod"  # Corrected production environment name with hyphen
route = "api-gateway.adevstack.workers.dev/*"
