
name = "api-gateway"  # Correct worker name with hyphen

compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]  # Enable Node.js compatibility

main = "./dist/index.js"

[build]
command = "npm run build"  # Ensure this matches the build process

[vars]
NODE_ENV = "production"

[env.production]
name = "api-gateway-prod"
route = "api-gateway.adevstack.workers.dev/*"
