
name = "api-gateway"
compatibility_date = "2024-04-28"
compatibility_flags = ["nodejs_compat"]
main = "./dist/index.js"

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"

[env.production]
vars = { NODE_ENV = "production" }
route = "api-gateway.adevstack.workers.dev/*"
