
name = "api-gateway"  # with a hyphen "-", matching Cloudflare project name

compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[site]
bucket = "./dist/public"

[vars]
NODE_ENV = "production"

[env.production]
name = "api-gateway-prod"
route = "api-gateway.adevstack.workers.dev/*"

[[env.production.routes]]
pattern = "/api/*"
script = "api-gateway-prod"
